name: CI/CD Pipeline

on:
  push:
    branches: ["main"]

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # 2️⃣ Login to DockerHub
      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # 3️⃣ Build Docker image
      - name: Build image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/cicd-app:latest .

      # 4️⃣ Push Docker image
      - name: Push image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/cicd-app:latest

      # 5️⃣ Deploy on EC2
      - name: Deploy on EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}         # EC2 public IP
          username: ec2-user                     # use ubuntu if Ubuntu AMI
          key: ${{ secrets.EC2_SSH_KEY }}       # PRIVATE key content here
          port: 22                               # default SSH port
          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/cicd-app:latest
            docker stop app || true
            docker rm app || true
            docker run -d --name app -p 80:80 ${{ secrets.DOCKER_USERNAME }}/cicd-app:latest
